using System.Collections.Generic;

namespace Blockfall.Core.Localization;

/// <summary>
/// Korean UI translations, keyed by the exact English source string used at the
/// call site. Any wrapped string with no entry here falls back to English, so the
/// table can grow incrementally. Pure-punctuation/format templates (e.g. "{0} {1}",
/// "CPU · {0}") are intentionally omitted — translating them would just reproduce
/// the source. Grouped by screen; shared keys live at the top.
/// </summary>
internal static class LocData
{
    internal static readonly Dictionary<string, string> Korean = new()
    {
        // ---- Shared / common ----------------------------------------------
        ["BACK"] = "뒤로",
        ["MENU"] = "메뉴",
        ["SCORE"] = "점수",
        ["LINES"] = "라인",
        ["LEVEL"] = "레벨",
        ["TIME"] = "시간",
        ["SEED"] = "시드",
        ["TETRISES"] = "테트리스",
        ["T-SPINS"] = "T-스핀",
        ["FINESSE"] = "피네스",
        ["PROFILE"] = "프로필",
        ["STORE"] = "상점",
        ["REPLAYS"] = "리플레이",
        ["SETTINGS"] = "설정",
        ["PAUSED"] = "일시정지",
        ["RESUME"] = "계속하기",
        ["YOU WIN!"] = "승리!",
        ["DEFEATED"] = "패배",
        ["REMATCH"] = "재대결",
        ["OPPONENT LEFT"] = "상대가 나갔습니다",

        // ---- Main menu ----------------------------------------------------
        ["PLAY"] = "플레이",
        ["DAILY CHALLENGE"] = "일일 챌린지",
        ["ONE SEED, ONE SHOT · NEW SEED IN {0}H {1}M"] = "하나의 시드, 한 번의 도전 · 새 시드까지 {0}시간 {1}분",
        ["VERSUS CPU"] = "CPU 대전",
        ["GARBAGE BATTLE · FIVE DIFFICULTIES"] = "방해 블록 배틀 · 5단계 난이도",
        ["CUSTOM RUN"] = "커스텀 런",
        ["MODIFIERS STACK ON ANY RUN · MODIFIED RUNS SET NO RECORDS"] = "모디파이어는 모든 런에 중첩 · 변경된 런은 기록되지 않음",
        ["SEED CODE OR ANY WORD"] = "시드 코드 또는 아무 단어",
        ["PLAY SEED"] = "시드 플레이",
        ["HOW TO PLAY"] = "게임 방법",
        ["FIRST RUN"] = "첫 도전",
        ["Original brand — not affiliated with Tetris®."] = "독자 브랜드 — Tetris®와 무관합니다.",

        // Mode titles (display only — the GameModeId enum is the persisted key).
        ["MARATHON"] = "마라톤",
        ["SPRINT 40"] = "스프린트 40",
        ["ULTRA 2:00"] = "울트라 2:00",
        ["ZEN"] = "젠",
        ["DIG RACE"] = "디그 레이스",
        ["SURVIVAL"] = "서바이벌",
        ["MASTER 20G"] = "마스터 20G",
        // Mode blurbs.
        ["CLIMB TO LEVEL 15"] = "레벨 15까지 오르기",
        ["40 LINES, FASTEST TIME"] = "40라인, 최단 시간",
        ["MAX SCORE IN 2 MINUTES"] = "2분간 최고 점수",
        ["NO PRESSURE, NO END"] = "부담 없이, 끝없이",
        ["DIG THROUGH THE GARBAGE"] = "방해 블록 파헤치기",
        ["THE FLOOR KEEPS RISING"] = "바닥이 계속 차오른다",
        ["INSTANT GRAVITY"] = "즉시 낙하 중력",

        // Run modifiers (from core ModifierSet.Label).
        ["NO HOLD"] = "홀드 없음",
        ["NO GHOST"] = "고스트 없음",
        ["LOW-G"] = "저중력",
        ["BLITZ"] = "블리츠",
        ["HARD LOCK"] = "하드 락",
        ["ALL-SPIN"] = "올 스핀",
        ["INVISIBLE"] = "인비저블",

        // ---- Settings -----------------------------------------------------
        ["LANGUAGE"] = "언어",
        ["SKIN"] = "스킨",
        ["AUDIO"] = "오디오",
        ["VISUAL"] = "화면",
        ["HANDLING"] = "조작",
        ["SFX VOLUME"] = "효과음 볼륨",
        ["MUSIC VOLUME"] = "음악 볼륨",
        ["MUTE"] = "음소거",
        ["GHOST PIECE"] = "고스트 블록",
        ["COLORBLIND PALETTE"] = "색약 팔레트",
        ["FINESSE METER"] = "피네스 미터",
        ["NEON GLOW (BLOOM)"] = "네온 글로우 (블룸)",
        ["REDUCED MOTION"] = "모션 줄이기",
        ["JUICE / SHAKE"] = "이펙트 / 흔들림",
        ["FULLSCREEN"] = "전체 화면",
        ["DAS (DELAY)"] = "DAS (지연)",
        ["ARR (REPEAT)"] = "ARR (반복)",
        ["DRAG CONTROLS (TOUCH)"] = "드래그 조작 (터치)",
        ["UNAVAILABLE ON THIS DEVICE"] = "이 기기에서 사용 불가",
        ["ON"] = "켜짐",
        ["OFF"] = "꺼짐",
        // Controls (keyboard remap)
        ["CONTROLS"] = "키 설정",
        ["CLICK A KEY, THEN PRESS THE NEW ONE"] = "키를 누른 뒤 새 키를 입력하세요",
        ["PRESS A KEY…"] = "키를 누르세요…",
        ["RESET TO DEFAULTS"] = "기본값으로 초기화",
        ["MOVE LEFT"] = "왼쪽 이동",
        ["MOVE RIGHT"] = "오른쪽 이동",
        ["SOFT DROP"] = "소프트 드롭",
        ["HARD DROP"] = "하드 드롭",
        ["ROTATE CW"] = "시계 방향 회전",
        ["ROTATE CCW"] = "반시계 방향 회전",
        ["ROTATE 180"] = "180도 회전",
        ["PAUSE"] = "일시정지",
        // Accessibility
        ["ACCESSIBILITY"] = "접근성",
        ["TEXT SIZE"] = "글자 크기",
        ["BLOCK COLORS · APPLIES INSTANTLY"] = "블록 색상 · 즉시 적용",
        ["MORE SKINS IN THE STORE"] = "상점에서 더 많은 스킨",
        ["ACTIVE"] = "사용 중",

        // ---- In-game HUD --------------------------------------------------
        ["GOAL"] = "목표",
        ["HOLD"] = "홀드",
        ["NEXT"] = "다음",
        ["✓ CLEAN"] = "✓ 완벽",
        ["CLEAN ×{0}"] = "완벽 ×{0}",
        ["{0} left"] = "{0} 남음",
        ["{0} rows"] = "{0} 줄",

        // ---- In-game overlays (pause / revive / ghost) --------------------
        ["GHOST"] = "고스트",
        ["GHOST  {0}{1}"] = "고스트  {0}{1}",
        ["SECOND CHANCE?"] = "다시 한 번?",
        ["WIPE THE BOARD, KEEP YOUR RUN.\nREVIVED RUNS SET NO RECORDS."] = "보드를 비우고 게임을 이어가세요.\n부활한 게임은 기록으로 남지 않습니다.",
        ["USE SECOND CHANCE ({0} LEFT)"] = "다시 한 번 사용 ({0}개 남음)",
        ["WATCH AD TO REVIVE"] = "광고 보고 부활하기",
        ["GIVE UP"] = "포기하기",
        ["QUIT TO MENU"] = "메뉴로 나가기",

        // ---- Versus (CPU + online) ---------------------------------------
        ["YOU"] = "나",
        ["VS CPU · {0}"] = "CPU 대전 · {0}",
        ["YOU {0}"] = "나 {0}",
        ["CPU {0}"] = "CPU {0}",
        ["INCOMING +{0}"] = "공격 +{0}",
        ["SENT +{0}"] = "보냄 +{0}",
        ["YOU {0}  ·  CPU {1}"] = "나 {0}  ·  CPU {1}",
        ["YOU   {0}L"] = "나   {0}L",
        ["YOU   {0}L · SENT {1}"] = "나   {0}줄 · 보냄 {1}",
        ["{0}   {1}L · SENT {2}"] = "{0}   {1}줄 · 보냄 {2}",
        ["LEAVE THE MATCH?"] = "경기를 나갈까요?",
        ["KEEP PLAYING"] = "계속하기",
        ["FORFEIT"] = "기권",
        ["WAITING FOR OPPONENT…"] = "상대를 기다리는 중…",
        ["WAITING FOR HOST…"] = "호스트를 기다리는 중…",
        ["{0} WANTS A REMATCH"] = "{0}님이 재대결을 원합니다",
        ["STARTING…"] = "시작하는 중…",

        // ---- Results screen ----------------------------------------------
        ["CLEAR!"] = "클리어!",
        ["GAME OVER"] = "게임 오버",
        ["NEW BEST"] = "신기록",
        ["ACHIEVEMENT: {0}"] = "업적: {0}",
        ["MAX COMBO"] = "최대 콤보",
        ["PIECES/S"] = "초당 블록",
        ["SENT"] = "보낸 방해",
        ["FAULTS"] = "실수",
        ["BEST STREAK"] = "최고 연속",
        ["MODS"] = "모디파이어",
        ["PLAY AGAIN"] = "다시 하기",
        ["WATCH REPLAY"] = "리플레이 보기",
        ["SAVE REPLAY"] = "리플레이 저장",
        ["SAVED"] = "저장됨",
        ["SAVE FAILED"] = "저장 실패",
        ["SHARE CODE"] = "코드 공유",
        ["COPIED"] = "복사됨",
        ["REPLAY SEED"] = "시드 재도전",

        // ---- Profile screen ----------------------------------------------
        ["GAMES PLAYED"] = "플레이 횟수",
        ["TOTAL SCORE"] = "총 점수",
        ["LINES CLEARED"] = "제거한 라인",
        ["PIECES PLACED"] = "배치한 블록",
        ["TIME PLAYED"] = "플레이 시간",
        ["PERFECT CLEARS"] = "퍼펙트 클리어",
        ["BEST COMBO"] = "최고 콤보",
        ["BEST BACK-TO-BACK"] = "최고 백투백",
        ["BEST PIECES/SEC"] = "최고 초당 블록",
        ["{0} / {1} UNLOCKED"] = "{0} / {1} 달성",
        ["No entries yet — play this mode to rank."] = "기록이 없습니다 — 이 모드를 플레이해 순위에 등록하세요.",
        ["{0}h {1}m"] = "{0}시간 {1}분",
        ["{0}m"] = "{0}분",

        // ---- Store screen -------------------------------------------------
        ["THEMES"] = "테마",
        ["BURST FX"] = "클리어 연출",
        ["BLOCK FIT · DRAG & FIT, NO GRAVITY"] = "블록 핏 · 끼워 맞추기, 중력 없음",
        ["BOOSTERS"] = "부스터",
        ["PREMIUM"] = "프리미엄",
        ["RESTORE PURCHASES"] = "구매 복원",
        ["EQUIPPED"] = "장착됨",
        ["EQUIP"] = "장착",
        ["{0}   ·   OWNED: {1}"] = "{0}   ·   보유: {1}",

        // ---- Replays screen ----------------------------------------------
        ["paste a replay share code"] = "리플레이 공유 코드 붙여넣기",
        ["IMPORT"] = "가져오기",
        ["No saved replays yet — save one from the results screen."] = "저장된 리플레이가 없습니다 — 결과 화면에서 저장하세요.",
        ["{0} lines · {1}"] = "{0}줄 · {1}",
        ["WATCH"] = "보기",

        // ---- Versus select screen ----------------------------------------
        ["ONLINE MATCH"] = "온라인 대전",
        ["DUEL A FRIEND — HOST OR JOIN BY IP"] = "친구와 대결 — 방 만들기 또는 IP로 참가",
        ["OR CHOOSE A CPU OPPONENT"] = "또는 CPU 상대를 선택하세요",
        ["EASY"] = "쉬움",
        ["NORMAL"] = "보통",
        ["HARD"] = "어려움",
        ["MASTER"] = "마스터",
        ["GRANDMASTER"] = "그랜드마스터",

        // ---- Ranked ladder (tiers + readouts) -----------------------------
        // MASTER / GRANDMASTER reuse the CPU-difficulty translations above.
        ["BRONZE"] = "브론즈",
        ["SILVER"] = "실버",
        ["GOLD"] = "골드",
        ["PLATINUM"] = "플래티넘",
        ["DIAMOND"] = "다이아몬드",
        ["YOUR RANK: UNRANKED"] = "내 랭크: 미배치",
        ["YOUR RANK: {0} · {1}  ({2}W {3}L)"] = "내 랭크: {0} · {1}  ({2}승 {3}패)",
        ["RANK {0}  ({1}{2}) · {3}"] = "랭크 {0}  ({1}{2}) · {3}",

        // ---- Online lobby -------------------------------------------------
        ["SERVERLESS 1V1 — SAME WIFI, OR THE HOST FORWARDS PORT 7777"] = "서버리스 1대1 — 같은 와이파이, 또는 호스트가 7777 포트 개방",
        ["HOST A MATCH"] = "방 만들기",
        ["YOUR ADDRESS: {0}"] = "내 주소: {0}",
        ["YOUR ADDRESS: (NO LAN ADDRESS FOUND)"] = "내 주소: (LAN 주소를 찾을 수 없음)",
        ["OPEN ROOM"] = "방 열기",
        ["JOIN A MATCH"] = "방 참가",
        ["HOST IP  (E.G. 192.168.0.10)"] = "호스트 IP  (예: 192.168.0.10)",
        ["JOIN"] = "참가",
        ["QUICK MATCH  —  FIND ANY OPPONENT ONLINE"] = "빠른 대전  —  온라인 상대 자동 찾기",
        ["matchmaker url (ws://host:8080)"] = "매치메이커 URL (ws://host:8080)",
        ["FIND MATCH"] = "상대 찾기",
        // Online lobby status messages.
        ["COULD NOT OPEN PORT {0} ({1})"] = "{0} 포트를 열 수 없습니다 ({1})",
        ["ROOM OPEN ON PORT {0} — WAITING FOR AN OPPONENT…"] = "{0} 포트에서 방이 열렸습니다 — 상대를 기다리는 중…",
        ["ENTER THE HOST'S IP FIRST"] = "먼저 호스트의 IP를 입력하세요",
        ["COULD NOT CONNECT ({0})"] = "연결할 수 없습니다 ({0})",
        ["CONNECTING TO {0}:{1}…"] = "{0}:{1}에 연결하는 중…",
        ["ENTER THE MATCHMAKER URL FIRST"] = "먼저 매치메이커 주소를 입력하세요",
        ["MATCH FOUND — VS {0}"] = "상대를 찾았습니다 — VS {0}",
        ["SEARCHING FOR AN OPPONENT…"] = "상대를 찾는 중…",
        ["CONNECTED — SHAKING HANDS…"] = "연결됨 — 핸드셰이크 중…",
        ["CONNECTION LOST"] = "연결이 끊겼습니다",
        ["VERSION MISMATCH — BOTH PLAYERS NEED THE SAME BUILD"] = "버전 불일치 — 두 플레이어 모두 같은 빌드여야 합니다",

        // ---- Tutorial -----------------------------------------------------
        ["MOVE  —  slide the piece left and right"] = "이동  —  블록을 좌우로 움직이기",
        ["◀  ▶  arrow keys"] = "◀  ▶  방향키",
        ["◀  ▶  buttons"] = "◀  ▶  버튼",
        ["ROTATE  —  turn the piece"] = "회전  —  블록을 돌리기",
        ["▲ (or Z)"] = "▲ (또는 Z)",
        ["SOFT DROP  —  hold to fall faster"] = "소프트 드롭  —  길게 눌러 빠르게 내리기",
        ["▼ down arrow"] = "▼ 아래 방향키",
        ["▼ button"] = "▼ 버튼",
        ["HARD DROP  —  slam it straight down"] = "하드 드롭  —  단숨에 바닥까지 내리기",
        ["SPACE"] = "스페이스",
        ["⤓ button"] = "⤓ 버튼",
        ["HOLD  —  stash a piece for later"] = "홀드  —  블록을 잠시 보관하기",
        ["H button"] = "H 버튼",
        ["CLEAR A LINE  —  fill the row, drop into the gap"] = "라인 클리어  —  줄을 채우고 빈 칸에 넣기",
        ["fill the bottom row"] = "맨 아래 줄을 채우기",
        ["T-SPIN  —  rotate a T into the notch for bonus points"] = "T-스핀  —  T를 홈에 돌려 넣어 보너스 점수 얻기",
        ["spin the T (▲ / Z) into the slot"] = "T를 (▲ / Z) 돌려 홈에 넣기",
        ["spin the T (↻ / ↺) into the slot"] = "T를 (↻ / ↺) 돌려 홈에 넣기",
        ["DEFEND  —  clear a line to fight off incoming garbage"] = "방어  —  줄을 지워 들어오는 방해 블록 막기",
        ["fill the gap to clear a garbage row"] = "빈 칸을 채워 방해 줄을 지우기",
        ["ALL SET  —  you're ready to play!"] = "준비 완료  —  이제 플레이할 수 있어요!",
        ["SKIP"] = "건너뛰기",

        // ---- Descent (charm-draft gauntlet) --------------------------------
        ["DESCENT"] = "디센트",
        ["PLACE & SURVIVE · GARBAGE KEEPS RISING"] = "배치 서바이벌 · 밀려오는 가비지",
        ["FIVE STRATA · DRAFT CHARMS · GO DEEP"] = "다섯 지층 · 참 드래프트 · 더 깊이",
        ["DRAFT CHARMS, DIVE DEEP"] = "참을 모아 더 깊이 강하",
        ["DEPTH {0}/{1}"] = "깊이 {0}/{1}",
        ["NEXT: DEPTH {0}/{1}"] = "다음: 깊이 {0}/{1}",
        ["DIG"] = "굴착",
        ["BURST"] = "버스트",
        ["SIEGE"] = "공성",
        ["STRATUM {0} CLEARED!"] = "지층 {0} 돌파!",
        ["STRATUM {0}"] = "지층 {0}",
        ["BANKED {0}"] = "적립 {0}",
        ["CHOOSE A CHARM"] = "참 선택",
        ["SKIP (+{0} BANK)"] = "건너뛰기 (+{0} 적립)",
        ["OWNED: {0}"] = "보유: {0}",
        ["BOTTOM REACHED!"] = "최심부 도달!",
        ["RUN OVER"] = "런 종료",
        ["DEPTH"] = "깊이",
        ["BANKED SCORE"] = "적립 점수",
        ["DESCEND AGAIN"] = "다시 강하",
        ["CHARMS"] = "참",

        // Charm names (short display labels).
        ["GREED"] = "탐욕",
        ["PROPHET"] = "예언자",
        ["SPIN SAGE"] = "스핀 현자",
        ["ANCHOR"] = "닻",
        ["GAMBLER"] = "도박사",
        ["FEATHER"] = "깃털",
        ["BLINDFOLD"] = "눈가리개",
        ["MONK"] = "수도승",
        ["SAPPER"] = "공병",
        ["WARLORD"] = "군주",
        ["HOURGLASS"] = "모래시계",
        ["JUGGERNAUT"] = "거신",

        // Charm trade descriptions (reward - price).
        ["Score x1.5 - pieces fall 40% faster"] = "점수 ×1.5 — 블록 낙하 40% 빨라짐",
        ["+2 next previews - Hold is sealed"] = "NEXT 미리보기 +2 — 홀드 봉인",
        ["Every spin scores - lock delay 0.35s"] = "모든 스핀에 점수 — 락 딜레이 0.35초",
        ["Lock delay 0.8s - score x0.9"] = "락 딜레이 0.8초 — 점수 ×0.9",
        ["Score x2.0 - lock delay 0.15s"] = "점수 ×2.0 — 락 딜레이 0.15초",
        ["Gravity 60% slower - timed stages 15% shorter"] = "중력 60% 느려짐 — 시간제 지층 15% 짧아짐",
        ["No ghost piece - score x1.25"] = "고스트 표시 없음 — 점수 ×1.25",
        ["Hold is sealed - score x1.3"] = "홀드 봉인 — 점수 ×1.3",
        ["2 fewer garbage rows, slower rise - score x0.8"] = "가비지 2줄 감소·상승 둔화 — 점수 ×0.8",
        ["Siege goals 4 lines lighter - Burst 15s shorter"] = "공성 목표 4줄 감소 — 버스트 15초 짧아짐",
        ["Timed stages +20s - score x0.85"] = "시간제 지층 +20초 — 점수 ×0.85",
        ["Gravity 20% slower - siege goals +3"] = "중력 20% 느려짐 — 공성 목표 +3",
    };
}
